// Copyright 2024 Arthur Lugovoy (@artlugovoy)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define EE_HANDS

#define SPI_SCK_PIN GP2
#define SPI_MOSI_PIN GP3
#define SPI_MISO_PIN GP0

#define ROTATIONAL_TRANSFORM_ANGLE  -25
#define POINTING_DEVICE_INVERT_X
#define POINTING_DEVICE_RIGHT
#define PMW33XX_CS_PIN GP1
#define PMW33XX_CPI 800
#define POINTING_DEVICE_TASK_THROTTLE_MS 1
#define PMW33XX_LIFTOFF_DISTANCE 0x02

#define SPLIT_POINTING_ENABLE
//#define RGBLIGHT_LED_COUNT 18
//#define RGBLIGHT_MODE_RAINBOW_SWIRL
//#define WS2812_DI_PIN GP22

#define SPLIT_USB_DETECT
#define SPLIT_USB_TIMEOUT_POLL 10
#define SPLIT_WATCHDOG_ENABLE
#define SPLIT_WATCHDOG_TIMEOUT 3000
