# This file intentionally left blank
SPLIT_KEYBOARD = yes
SERIAL_DRIVER = vendor
POINTING_DEVICE_DRIVER = pmw3360
POINTING_DEVICE_ENABLE = yes
CONSOLE_ENABLE = yes
COMMAND_ENABLE = yes
MAGIC_KEY_DEBUG_MOUSE = yes

# RGBLIGHT_ENABLE = yes
# RGBLED_SPLIT = 18
# RGBLIGHT_DRIVER = ws2812
