#pragma once

#define EE_HANDS

#define SPI_SCK_PIN B1
#define SPI_MOSI_PIN B2
#define SPI_MISO_PIN B3
#define PMW33XX_CS_PIN B6

#define ROTATIONAL_TRANSFORM_ANGLE  -25
#define POINTING_DEVICE_LEFT
#define POINTING_DEVICE_ROTATION_90
#define POINTING_DEVICE_INVERT_X
#define PMW33XX_CPI 400
#define POINTING_DEVICE_TASK_THROTTLE_MS 1
#define PMW33XX_LIFTOFF_DISTANCE 0x01

#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 2
